// <auto-generated />
using CertificateService.Web.API.Data.Models;

namespace CertificateService.Web.API.Data.Resources
{
    /// <summary>
    /// A model representing constants.
    /// </summary>
    public class Constants
    {
        /// <summary>
        /// Constants for user roles.
        /// </summary>
        public class Role
        {
            public const string Admin = "Admin";
            public const string User = "User";
        }

        /// <summary>
        /// Constants for output data format.
        /// </summary>
        public class OutputData
        {
            public const string ContentType = "application/octet-stream";
            public const string FileNameDocx = "Certificate.docx";
            public const string FileNamePdf = "Certificate.pdf";
        }

        /// <summary>
        /// Constants for output data format.
        /// </summary>
        public class TemplateFile
        {
            public const string Name = nameof(StudentData.Name);
            public const string Surname = nameof(StudentData.Surname);
            public const string Patronymic = nameof(StudentData.Patronymic);
            public const string Course = "k";
            public const string Faculty = "f";
            public const string MonthOfGraduation = "meoe";
            public const string YearOfGraduation = "yeoe";
            public const string DayOfCertificateIssue = "doi";
            public const string MonthOfCertificateIssue = "moi";
            public const string YearOfCertificateIssue = "yoi";

            public static readonly string[] ForMaleToUnderline = { "він", "студентом" };
            public static readonly string[] ForFemaleToUnderline = { "(вона)", "(кою)" };
        }

        /// <summary>
        /// Array of month names in ukrainian in locative.
        /// </summary>
        public static readonly string[] LocativeUAMonthNames =
        {
            "січні", "лютому", "березні", "квітні", "травні", "червні", "липні", "серпні", "вересні", "жовтні", "листопаді", "грудні"
        };
    }
}
